# Variables
@baseUrl = http://localhost:3333

# Login
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "user@example.com"
}

###

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

@roomId = bbc11a50-33f4-4aab-b783-cbb16c81fd19

###

# Create interaction
# @name createInteraction
POST {{baseUrl}}/rooms/{{roomId}}/interactions
Content-Type: application/json

{
  "prompt": "Qual o conceito de X dentro de Y?"
}


###

# Get room interactions
# @name getRoomInteractions
GET {{baseUrl}}/rooms/{{roomId}}/interactions
###
# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
