services:
  chat-api-postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: chat-api
    ports:
      - 5432:5432
    volumes:
     - ./docker/setup/init.sql:/docker-entrypoint-initdb.d/init.sql